import { z } from "zod";

const dailyHoursSchema = z.number().finite().gt(0).max(24).refine(
  (hours) => Math.abs(hours * 100 - Math.round(hours * 100)) < 1e-8,
  "Stunden dürfen höchstens zwei Nachkommastellen haben.",
).nullable();

// This is a complete replacement: explicit null clears a previously configured day.
export const smMarketWeekdayHoursSchema = z.object({
  mo: dailyHoursSchema,
  di: dailyHoursSchema,
  mi: dailyHoursSchema,
  do: dailyHoursSchema,
  fr: dailyHoursSchema,
}).strict();

export function smMarketWeekdayColumns(hours: z.infer<typeof smMarketWeekdayHoursSchema>) {
  const decimal = (value: number | null) => value === null ? null : value.toFixed(2);
  // Counts and totals are generated by Postgres, never supplied by the client.
  return {
    mondayHours: decimal(hours.mo),
    tuesdayHours: decimal(hours.di),
    wednesdayHours: decimal(hours.mi),
    thursdayHours: decimal(hours.do),
    fridayHours: decimal(hours.fr),
  };
}
